#!/usr/bin/env python3
"""Offline graph invariants, plus installed registry checks called by Krea smoke."""
import json
from pathlib import Path
HERE=Path(__file__).resolve().parent

def validate_graph(g):
    nodes={n['id']:n for n in g['nodes']};links={l[0]:l for l in g['links']}
    if len(nodes)!=len(g['nodes']) or len(links)!=len(g['links']):raise ValueError('Duplicate graph ids')
    for lid,a,sa,b,sb,typ in links.values():
        src=nodes[a]['outputs'][sa];dst=nodes[b]['inputs'][sb]
        if src['type']!=typ or dst['type']!=typ or lid not in src['links'] or dst['link']!=lid or nodes[a]['order']>=nodes[b]['order']:
            raise ValueError('Broken or cyclic graph link')
    for n in nodes.values():
        if n.get('mode',0)!=0:raise ValueError('Shipped media graph must be active')
        if 'widgets_values_named' in n and list(n['widgets_values_named'].values())!=n['widgets_values']:raise ValueError('Widget serialization drift')
        for i,inp in enumerate(n['inputs']):
            lid=inp.get('link')
            if lid is not None and (lid not in links or links[lid][3:5]!=[n['id'],i]):raise ValueError('Dangling input')
        for i,out in enumerate(n['outputs']):
            for lid in out.get('links',[]):
                if lid not in links or links[lid][1:3]!=[n['id'],i]:raise ValueError('Dangling output')
    def one(typ):
        matches=[n for n in nodes.values() if n['type']==typ]
        if len(matches)!=1:raise ValueError('Expected one '+typ)
        return matches[0]
    def source(n,name):
        inp=next(i for i in n['inputs'] if i['name']==name)
        return nodes[links[inp['link']][1]]
    if one('UNETLoader')['widgets_values']!=['minimax_h3_ref2va_bf16.safetensors','default']:raise ValueError('Full BF16 diffusion required')
    if one('CLIPLoader')['widgets_values']!=['qwen3vl_32b_minimax_h3_bf16.safetensors','minimax','default']:raise ValueError('Full BF16 encoder required')
    if one('BasicScheduler')['widgets_values']!=['beta',25,1.0]:raise ValueError('HQ schedule drift')
    if one('KSamplerSelect')['widgets_values']!=['res_multistep']:raise ValueError('Sampler drift')
    if one('RandomNoise')['widgets_values']!=[42,'fixed']:raise ValueError('Comparison seed must be fixed')
    if one('CreateVideo')['widgets_values']!=[24.0,'auto','sRGB','none']:raise ValueError('Video encoding metadata drift')
    if source(one('CreateVideo'),'audio')['type']!='VAEDecodeAudio':raise ValueError('Never mux source reference audio')
    if source(one('VAEDecodeAudio'),'samples')['type']!='SamplerCustomAdvanced':raise ValueError('Audio must be generated by H3')
    for name in ('vae','audio_vae'):
        if source(one('H3MediaConditioning'),name)['type']!='VAELoader':raise ValueError('Both native reference VAEs required')
    if source(one('H3MediaSaveLastFrame'),'completed_export')['type']!='H3MediaExportVideo':raise ValueError('Final frame must follow encoded export')
    v=one('H3MediaVideoReference')['widgets_values_named']
    if v['visual_role']!='Ignore video (voice only)' or v['audio_role']!='Voice timbre - NEW dialogue':raise ValueError('Voice-only must be default')
    if any('Krea' in n['type'] or 'Rebalance' in n['type'] for n in nodes.values()):raise ValueError('Do not apply Krea conditioning patches to H3')
    return True

def validate_native_registry(registry):
    for name in ('MiniMaxH3ReferenceToVideo','LoadVideo','H3MediaVideoReference','H3MediaAudioReference','H3MediaConditioning'):
        if name not in registry:raise ValueError('Missing native/media node: '+name)
    schema=json.dumps(registry['MiniMaxH3ReferenceToVideo'])
    for field in ('ref_images','ref_videos','ref_audios','ref_video_audios','audio_vae','vae'):
        if field not in schema:raise ValueError('Native H3 schema lacks '+field)
    if 'VIDEO' not in registry['LoadVideo'].get('output',[]):raise ValueError('LoadVideo must supply a native VIDEO')

def static():
    files=sorted((HERE/'workflows').glob('*.json'))
    if len(files)!=1:raise ValueError('Expected one additive HQ media workflow')
    graphs=[json.loads(p.read_text()) for p in files]
    for g in graphs:validate_graph(g)
    print('H3 MEDIA STATIC PASS: BF16 native conditioning, MP4 roles, generated audio only, final-frame dependency. No inference run.',flush=True)
    return graphs

if __name__=='__main__':static()
