#!/usr/bin/env python3
"""Verify this complete source snapshot before Docker starts.

LoRA links are intentionally editable. Text line endings/BOM are normalized so
Windows checkout does not cause false mismatches. No network or writes are used.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re

SNAPSHOT = 'h3-1.5.0-krea-identity-1.0.0-r1'
MANIFEST = 'SOURCE_SNAPSHOT.json'
EDITABLE = {'config/lora_links.txt'}
IGNORE_DIRS = {'__pycache__', '.pytest_cache', '__MACOSX'}
IGNORE_FILES = {'.DS_Store', 'Thumbs.db'}


def normalized_sha256(path):
    data = Path(path).read_bytes().decode('utf-8-sig')
    data = data.replace('\r\n', '\n').replace('\r', '\n')
    return hashlib.sha256(data.encode('utf-8')).hexdigest()


def inventory(root):
    root = Path(root)
    result = set()
    for parent, directories, files in os.walk(root, followlinks=False):
        base = Path(parent)
        # Git metadata is not application source. Cache files are generated by tests.
        directories[:] = [d for d in directories if d not in IGNORE_DIRS
                           and not (base == root and d == '.git')]
        for name in directories + files:
            path = base / name
            if base == root and name == '.git':
                continue
            if path.is_symlink():
                raise ValueError('Unexpected source symlink: ' + str(path.relative_to(root)))
        for name in files:
            if name in IGNORE_FILES or name.startswith('._'):
                continue
            if base == root and name == '.git':
                continue
            result.add((base / name).relative_to(root).as_posix())
    return result


def verify(root):
    root = Path(root).resolve()
    manifest_path = root / MANIFEST
    if not manifest_path.is_file() or manifest_path.is_symlink():
        raise ValueError('Missing SOURCE_SNAPSHOT.json. Use the complete clean ZIP.')
    manifest = json.loads(manifest_path.read_text(encoding='utf-8-sig'))
    if manifest.get('snapshot') != SNAPSHOT:
        raise ValueError('Mixed snapshot/verifier versions. Replace the entire clean package.')
    rows = manifest.get('files')
    if not isinstance(rows, dict) or not rows:
        raise ValueError('Invalid source snapshot file list.')
    if set(manifest.get('editable_files', [])) != EDITABLE:
        raise ValueError('Unexpected editable-file policy in the snapshot.')
    for name, expected in rows.items():
        if not isinstance(name, str) or '\\' in name:
            raise ValueError('Invalid source snapshot path.')
        path = PurePosixPath(name)
        if path.is_absolute() or '..' in path.parts or '.git' in path.parts or ':' in name or name == MANIFEST:
            raise ValueError('Unsafe source snapshot path: ' + name)
        if name not in EDITABLE and (not isinstance(expected, str) or not re.fullmatch('[0-9a-f]{64}', expected)):
            raise ValueError('Invalid digest for: ' + name)
        if name in EDITABLE and expected is not None:
            raise ValueError('LoRA link contents must remain editable.')
    if not EDITABLE.issubset(rows):
        raise ValueError('The shared LoRA link file must be included.')
    observed = inventory(root)
    expected_paths = set(rows) | {MANIFEST}
    missing = sorted(expected_paths - observed)
    extra = sorted(observed - expected_paths)
    if missing:
        raise ValueError('Incomplete upload. Missing: ' + ', '.join(missing[:8]))
    if extra:
        raise ValueError('Unexpected files from an older/incorrect upload: ' + ', '.join(extra[:8]) +
                         '. Use the clean replacement instructions; do not merge old folders.')
    changed = []
    for name, expected in rows.items():
        if name in EDITABLE:
            # Inventory established the file exists; never inspect private URL contents.
            if not (root/name).is_file():raise ValueError('Missing shared LoRA list.')
            continue
        if normalized_sha256(root / name) != expected:
            changed.append(name)
    if changed:
        raise ValueError('Changed/truncated/older source files: ' + ', '.join(changed[:8]) +
                         '. Restore these files from this clean ZIP. LoRA links are exempt.')
    print(f'CLEAN SOURCE SNAPSHOT VERIFIED: {SNAPSHOT} | {len(rows)} files; LoRA links editable.', flush=True)
    return len(rows)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    try:
        verify(args.root)
    except (ValueError, OSError, UnicodeError) as exc:
        raise SystemExit('SOURCE SNAPSHOT ERROR: ' + str(exc)) from exc
